### ISSUE TITLE
IK_control_ft_L rotate/move incorrect

### ISSUE THREAD

**Issue by sykvbt1960** [animate1978/MB-Lab#166]
Please forgive my poor english.
my problem is when rotate or move the _IK_control_ft_L_, the toes part behave strangely.
the _IK_control_ft_R_  works fine. I'm using MB-Lab 1.7.6 and Blender v2.80.75.

![IK_control_ft_L](https://user-images.githubusercontent.com/56333708/67168592-ae0bb880-f3d8-11e9-8c2c-a7da794e2e0c.jpg)

Thank you and sorry to trouble you so much!

**Comment by animate1978** [comment]
Don't be sorry, this is what bug reports are for :)

I will look into it, though just to be safe you should do a test and Finalize the character first, then see if you get the same result.

**Comment by sykvbt1960** [comment]
Thanks for your quick reply.
After Finalize the character, the result still same, i try MBLab1.7.1, still the same, but it go fine with 1.6.2a version.
Please take a look of it when you have time and thanks for your hard working to keeping MBLab alive.
Thanks!

**Comment by sykvbt1960** [comment]
Hi, Sorry to bother you again.
i found out if i created the character with BOTH the "Use Inverse Kinematic" and "Use basic musics" options selected then everything is ok. 
Thanks a lot!

**Comment by mklemarczyk** [comment]
@sykvbt1960 Can I ask you to attach the blender file for investigation?
I want to investigate the situation, since strange behaviour was affecting only left side.

@animate1978 you can assign me to this issue. I will try to investigate it and report progress by November 11th.

**Comment by sykvbt1960** [comment]
@mklemarczyk  Thanks for your concern, here i attach the .blend file. actually just create a new character with use IK can get the same result.
by the way, the IK_control_hl_R also got a little strange reaction for the toes, but not so noticed...
here is the .blend file i generate, sorry i had to zip it cause i don't know how to attach the raw .blend file here. 
[IK issue.zip](https://github.com/animate1978/MB-Lab/files/3801188/IK.issue.zip)
Thanks for for you and all others who give work to MB-Lab. Thanks!

**Comment by mklemarczyk** [comment]
@sykvbt1960 no problem with zip, it will download faster. Thank you. I will look into it.

**Comment by mklemarczyk** [comment]
Is it the same behaviour if you finalise the character? I found that the character you sent is not finalised.
Setting the pose should be done after creation finalisation step.

**Comment by sykvbt1960** [comment]
@mklemarczyk thanks for your quick replied. 
yes, after finalized, the result is still the same, but if create the character with "Use basic musics" also selected, then everything seems ok.
by the way, i'm using MB-Lab 1.7.6 and blender v2.80.75.
thnaks again for both of you @mklemarczyk and @animate1978 !

**Comment by animate1978** [comment]
This should be fixed now, if you clone the "Developmental" branch

**Comment by mklemarczyk** [comment]
@animate1978 I will cross check it tomorrow and send results.

**Comment by mklemarczyk** [comment]
@animate1978 verified with commit 2c8c3a7 on dev branch. Problem still exists.

**Comment by animate1978** [comment]
![bad_ik_01](https://user-images.githubusercontent.com/479115/68638144-3ce68f00-04c6-11ea-8a85-08e230c2c801.png)

Ok I finally see what it's doing, for some time I could not figure out how to replicate this bug.

This is a finalized model as well.

**Comment by mklemarczyk** [comment]
I found the issue:
The armature MBLab_skeleton_base_ik in file humanoid_library.blend is wrong. The feet bones need to be fixed. Who is in charge of this file? I do not want to modify it, because it is basic blender file.

**Comment by mklemarczyk** [comment]
I started to think about better format for storing the information that are stored in this file. Current format makes it not possible to compare changes done within commit. The GitHub is not able to create diff .blend files.

**Comment by animate1978** [comment]
I am still on this, I might need to call for help on this one I don't know. Rigging is not one my strong suites.

As for changing the file formats, this has been discussed before, I have no issue with it really, I mean the mesh can be stored as say OBJ file format, however the shader information would have to remain in a blend file, unless we go Principled BSDF again, with the old texture maps back, and the work that Noizirom is doing for the hair shader could be expanded for the skin... anyway that is another topic for another issue.

**Comment by animate1978** [comment]
With this commit, the IK and the IK / Muscle rigs *SHOULD* be fixed now

https://github.com/animate1978/MB-Lab/commit/51cdec4c34034f71301cb36b7e124f498be603a4

I have done basic testing with both rigs, focusing on the feet since these were the trouble spots

**Comment by sykvbt1960** [comment]
@animate1978  Thanks to you and ALL other persons who involved in this bug fixed...
Thanks for all your hard working...
Thank You!
