### ISSUE TITLE
my Addon install is missing some features and not finalizing.

### ISSUE THREAD

**Issue by marvinweish** [animate1978/MB-Lab#347]
Hi, 
I have installed the addon on blender 2.93. Please help I am missing some features and as it is it cannot update and the censor checkbox is missing and also I cannot do any finalization. please find some screen-shots attached below. Thankyou.
![image](https://user-images.githubusercontent.com/68609675/121400194-f9812a80-c95f-11eb-9490-d12002eb6f4a.png)
![image](https://user-images.githubusercontent.com/68609675/121400236-0736b000-c960-11eb-9d90-29aa0f922f96.png)
![image](https://user-images.githubusercontent.com/68609675/121400629-7b715380-c960-11eb-9c8b-d3d3be567950.png)
![image](https://user-images.githubusercontent.com/68609675/121401940-fd15b100-c961-11eb-8c9f-dcef07a60ad0.png)

**Comment by ldo** [comment]
As a general rule, do not post screenshots of text messages. Copy and paste the text itself. That makes it easier for everybody concerned.

**Comment by marvinweish** [comment]
Sorry about that, Thank you for the correction will amend it right away.

**Comment by animate1978** [comment]
So it looks like you are using an slightly older version of MB-Lab, it had some bugs that were corrected a few months ago, you are going to want to download the last updated version here :

https://mblab.dev/download/mb-lab-1-7-8-5/

I use Blender 2.93 on Linux (Ubuntu 20.04) but regardless it functions just the same as Windows.

**Comment by marvinweish** [comment]
@animate1978 I have just installed version 1-7-8-5 and I am still not seeing any changes. the settings still look the same and I am still getting this error when I click on update.

Python: Traceback (most recent call last):
  File "C:\Users\Darasa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\addon_updater_ops.py", line 234, in execute
    updater.set_check_interval(
  File "C:\Users\Darasa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\MB-Lab\addon_updater.py", line 511, in set_check_interval
    raise ValueError("Enable must be a boolean value")
ValueError: Enable must be a boolean value

location: <unknown location>:-1

and the checkboxes are still not there 
![image](https://user-images.githubusercontent.com/68609675/121510532-680dc900-c9f0-11eb-8ca7-12bc4cd6f459.png)

I am on windows and I am running blender as an administrator during install.

**Comment by animate1978** [comment]
Hmm I can confirm this issue, honestly I haven't checked up on the updater code in some time so I am unsure how long it has been buggy.

**Comment by endeavor9x** [comment]
Can confirm the same issue on Windows 10 ver 20H2

**Comment by animate1978** [comment]
Seems there were some recent changes at CG Cookie's updater code so I will be replacing the current code for the updater in MB-Lab with the newest available here soon.

**Comment by animate1978** [comment]
The Auto Updater code has been fixed with the latest changes from CG Cookie. The fix has been pushed to the dev branch of MB-Lab.

**Comment by animate1978** [comment]
I just checked the preferences.py file, that was where the problems were.

Updating the code and pushing to the repo.
